include complete redirect rule feature
ArniDagur/python-adblock pull request #59
Opened 2022-02-16 04:22 UTC by x0day

hi, thanks for this project first, it helps me a lot.

in this PR, I complete some feature about scriptlet injection and redirect rules.

1. update adblock-rust => 0.4.3
2. add `include_redirect_urls` parameter for `FilterSet.add_filter_list` and `FilterSet.add_filters`
3. add `Engine.add_resource` method.
4. add `adblock.AddResourceError` Exception
5. add `redirect_type` for `BlockerResult`
6. add some tests for these functions.

2022-02-16 04:25 UTC, x0day commented
Some implementations refer to the https://github.com/brave/adblock-rust-ffi.

2022-02-17 20:02 UTC, ArniDagur requested changes

2022-02-17 20:02 UTC, ArniDagur commented on src/lib.rs
> +            let resource = br.redirect.unwrap();
Can you refactor this to get rid of the unwrap, and even the mutability? I'm thinking something like
```rust
let (redirect, redirect_type) = if let Some(resource) = br.redirect {
    // Code here...
} else {
    (None, None)
}
```

2022-02-18 02:26 UTC, x0day commented on src/lib.rs
> +                RustAddResourceError::InvalidBase64Content => Err(AddResourceError::new_err(
you are right, I also want do this as you think, but like the question above, I can't find any test case for `RustAddResourceError::InvalidUtf8Content` emmm..
so I left it with `AddResourceError`. so let me changed it.

2022-02-18 03:15 UTC, x0day commented on tests/test_exceptions.py
> +    assert "invalid base64 content" in str(exc.value)
https://github.com/brave/adblock-rust/blob/2288ff9e140272269f433f1a739f128fcd74e755/src/resources/mod.rs#L151

adblock will ensure any text contents are also valid utf8 when content_type is javascript or text. I added a test for it.

2022-02-22 01:55 UTC, x0day commented
@ArniDagur  still have something not ready to merge?

2022-02-26 21:07 UTC, closed without merging

2022-02-27 00:55 UTC, x0day commented
> Thank you for your contribution. This has been merged as https://github.com/ArniDagur/python-adblock/pull/60.

can you release a new version on pypi.org? thank you.